-- 코드를 작성해주세요

SELECT T.TOTAL_SCORE AS SCORE,E.EMP_NO,E.EMP_NAME,E.POSITION,E.EMAIL
FROM (
    SELECT EMP_NO, SUM(SCORE) AS TOTAL_SCORE
    FROM HR_GRADE
    WHERE YEAR=2022
    GROUP BY EMP_NO
) AS T
JOIN HR_EMPLOYEES AS E
  ON T.EMP_NO=E.EMP_NO
WHERE T.TOTAL_SCORE=(
    SELECT MAX(X.TOTAL_SCORE)
    FROM (
        SELECT EMP_NO, SUM(SCORE) AS TOTAL_SCORE
        FROM HR_GRADE
        WHERE YEAR=2022
        GROUP BY EMP_NO
    ) AS X
)
